### ISSUE TITLE
Im getting this error, any ideas?

### ISSUE THREAD

**Issue by baskettcase** [relikd/abcddb2vcard#2]
Traceback (most recent call last):
  File "/Users/murlyn/Downloads/abcddb2vcard-main/abcddb2vcard/abcddb2vcard.py", line 52, in <module>
    main()
  File "/Users/murlyn/Downloads/abcddb2vcard-main/abcddb2vcard/abcddb2vcard.py", line 44, in main
    contacts = ABCDDB.load(args.input)
  File "/Users/murlyn/Downloads/abcddb2vcard-main/abcddb2vcard/ABCDDB.py", line 423, in load
    records = Record.queryAll(cur)
  File "/Users/murlyn/Downloads/abcddb2vcard-main/abcddb2vcard/ABCDDB.py", line 284, in queryAll
    return {x[0]: Record(x) for x in cursor.execute('''
sqlite3.OperationalError: no such column: ZTHUMBNAILIMAGEDATA

**Comment by baskettcase** [comment]
Ok I modified the code to remove that column since it doesn't exist in my database. I then had to remove all the image processing code and I was able to get it to export. Thanks!

**Comment by baskettcase** [comment]
btw adding this allowed me to export as individual files since the one file it kept breaking on some of the entries and would only import like 70 out of 1400 contacts. 

`contacts = ABCDDB.load(args.input)

    output_directory = Path(args.output)  # Assuming args.output is a directory path

    for rec in contacts:
        # Generate a unique filename for each contact
        # For example, use first name and last name, and ensure it's a valid filename
        filename = "{}_{}.vcf".format(rec.firstname, rec.lastname).replace(" ", "_")
        filepath = output_directory / filename

        try:
            with open(filepath, 'w') as f:
                f.write(rec.makeVCard())
            print(f'Contact {rec.firstname} {rec.lastname} written to {filename}')
        except Exception as e:
            print(f"Error processing contact {rec.firstname} {rec.lastname}: {e}", file=sys.stderr)

if __name__ == '__main__':
    main()`

**Comment by relikd** [comment]
"it kept breaking on some of the entries" can you tell me more info on the breaking entries? An example would be fantastic so I can fix whatever is causing it. I will release a new version with your suggestions soon. ... EDIT: release available now

**Comment by relikd** [comment]
Bump. Any news? Is it fixed with the new release? Are some entries still missing? Can this issue be closed?

**Comment by relikd** [comment]
closing due to inactivity
